/*
 * Decider — tap the coin on the home screen, a coin is tossed, and it lands on
 * "APPROVED BY DANNY" or "DISAPPROVED BY DANNY". 50/50 from the hardware RNG.
 *
 * Third .ino in the Badge sketch. Arduino concatenates Badge.ino first, then the others in
 * alphabetical order (Decider, Gallery), so this file sees Badge.ino's globals (gfx, panel,
 * screen, showScreen, centred, bootButtonHit, ...). Same rule as Gallery.ino: keep function
 * signatures to primitive types, or Arduino's auto-generated prototypes break the build.
 *
 * Assets: decider_assets.h, generated by tools/prep_decider.py from
 * Downloads\ThanksDanny\chooser\{positive.png, negative.jpg}. They are raw RGB565 compiled into
 * the app (about 1 MB of the 4.8 MB app partition), so there is no JPEG decode on the badge and
 * no filesystem reflash - the picture cache on LittleFS is untouched.
 *
 * The animation, all composed in the PSRAM canvas and sent one frame per flush (~46 ms):
 *   1. toss   : the coin rises from low on the screen, flips end over end (its face squashes
 *               to an edge and back), grows as it comes "closer", and falls back while the
 *               spin slows. Its shadow on the floor shrinks as it rises.
 *   2. land   : the spin is planned so the last half-turn ends on the chosen face.
 *   3. reveal : the landed coin zooms up into the full-screen badge.
 *   4. result : after a moment a bottom pill appears - AGAIN | HOME. A tap anywhere above the
 *               pill tosses again; BOOT goes home from anywhere, as everywhere else.
 *
 * Sound (v2.4): a drum roll plays while the coin is in the air and a cymbal crash hits on the
 * frame it lands. decider_sound.h is the user's drummroll.mp3 cut by tools/prep_decider_sound.py:
 * the roll trimmed to DEC_TOSS_MS and crossfaded into the original crash, 16 kHz mono PCM in
 * flash (~128 kB). The toss is therefore TIMED (DEC_TOSS_MS) rather than counted in frames, so
 * picture and sound stay together whatever the frame rate turns out to be.
 *
 * Audio path (proven by AudioProbe): ESP32-S3 I2S -> ES8311 codec @ 0x18 (configured over I2C,
 * the same bus as the touch controller) -> amplifier enabled by GPIO 46. es8311.c/.h are
 * Waveshare's vendored copy of Espressif's driver, taken from AudioProbe unchanged. Samples are
 * fed by a small FreeRTOS task on core 0, so the animation on core 1 never waits for audio. The
 * amp is switched off after each play so the speaker does not hiss or hum while idle.
 */

#include "decider_assets.h"
#include "decider_sound.h"
#include "ESP_I2S.h"
#include "es8311.h"

#define DEC_TOSS_MS    2400        // the throw; MUST match TOSS_MS in tools/prep_decider_sound.py
#define DEC_TURNS      6           // full end-over-end turns before landing
#define DEC_ZOOM       10          // frames for the coin-to-full-screen zoom
#define DEC_HINT_MS    1200        // clean result shown this long before the pill appears

// Result pill, inside the bottom of the circle: the chord at y=412..446 is ~250 px wide.
#define DEC_PILL_X 123
#define DEC_PILL_Y 410
#define DEC_PILL_W 220
#define DEC_PILL_H 36

static uint16_t *decBg = nullptr;         // the toss backdrop, built once in PSRAM
static int  decResult  = -1;              // 1 approved, 0 disapproved, -1 nothing yet
static uint32_t decTosses = 0, decYes = 0;

// Dirty rectangle of the last coin frame, so each frame restores only that patch of backdrop
// instead of copying the whole 434 kB (the copy alone was ~20 ms).
static int decDX0 = 0, decDY0 = 0, decDX1 = 465, decDY1 = 465;

// ---------------------------------------------------------------- backdrop

// A dark navy radial glow, the badge's own colour, with a faint lighter floor where the coin's
// shadow falls. Built once; about 20 ms.
void decMakeBg() {
  if (decBg) return;
  decBg = (uint16_t *)ps_malloc((size_t)LCD_WIDTH * LCD_HEIGHT * 2);
  if (!decBg) { Serial.println("decider: no PSRAM for the backdrop"); return; }
  for (int y = 0; y < LCD_HEIGHT; y++) {
    for (int x = 0; x < LCD_WIDTH; x++) {
      float dx = (x - 233) / 233.0f, dy = (y - 200) / 233.0f;
      float d = sqrtf(dx * dx + dy * dy);
      float k = 1.0f - d; if (k < 0) k = 0;
      float fy = (y - 395) / 26.0f, fx = (x - 233) / 150.0f;     // floor glow
      float fl = 1.0f - (fx * fx + fy * fy); if (fl < 0) fl = 0;
      int r = 3 + (int)(22 * k) + (int)(10 * fl);
      int g = 4 + (int)(30 * k) + (int)(12 * fl);
      int b = 10 + (int)(62 * k) + (int)(20 * fl);
      decBg[y * LCD_WIDTH + x] = RGB565(r, g, b);
    }
  }
}

// Copy the backdrop back over a rectangle of the canvas.
void decRestore(int x0, int y0, int x1, int y1) {
  uint16_t *fb = gfx->getFramebuffer();
  if (x0 < 0) x0 = 0; if (y0 < 0) y0 = 0;
  if (x1 > LCD_WIDTH - 1) x1 = LCD_WIDTH - 1; if (y1 > LCD_HEIGHT - 1) y1 = LCD_HEIGHT - 1;
  if (x1 < x0 || y1 < y0) return;
  for (int y = y0; y <= y1; y++)
    memcpy(fb + y * LCD_WIDTH + x0, decBg + y * LCD_WIDTH + x0, (size_t)(x1 - x0 + 1) * 2);
}

// ---------------------------------------------------------------- drawing a disc from a picture

// Draw `src` (a size x size round picture) as a disc of radius R at (cx, cy), squashed
// vertically by `squash` (1 = flat-on, 0 = edge-on). Nearest-neighbour sampling, clipped to the
// panel. This is both the flipping coin face and the zoom into the full-screen result.
void decDisc(const uint16_t *src, int size, int cx, int cy, int R, float squash) {
  if (R < 1) return;
  uint16_t *fb = gfx->getFramebuffer();
  int H = (int)(R * squash);
  if (H < 1) H = 1;
  for (int dy = -H; dy <= H; dy++) {
    int y = cy + dy;
    if (y < 0 || y >= LCD_HEIGHT) continue;
    float v = (float)dy / (float)H;                 // -1..1 down the squashed face
    int sy = (int)((v * 0.5f + 0.5f) * (size - 1) + 0.5f);
    float hw = R * sqrtf(fmaxf(0.0f, 1.0f - v * v));
    int x0 = cx - (int)hw, x1 = cx + (int)hw;
    if (x0 < 0) x0 = 0;
    if (x1 > LCD_WIDTH - 1) x1 = LCD_WIDTH - 1;
    const uint16_t *row = src + (size_t)sy * size;
    uint16_t *out = fb + y * LCD_WIDTH;
    float step = (float)(size - 1) / (2.0f * R);
    float sxf = (x0 - cx + R) * step;
    for (int x = x0; x <= x1; x++, sxf += step) {
      int sx = (int)sxf;
      if (sx > size - 1) sx = size - 1;
      out[x] = row[sx];
    }
  }
}

// One coin at angle `theta` (end-over-end): a dark gold edge peeking out on the side turned away,
// a bright gold rim, and the face - approved while cos(theta) > 0, disapproved while < 0.
void decCoin(int cx, int cy, int R, float theta) {
  float c = cosf(theta), s = sinf(theta);
  float sq = fabsf(c);
  int edge = (int)(R * 0.10f * s);                  // thickness showing as it turns
  gfx->fillEllipse(cx, cy + edge, R + 5, (int)((R + 5) * sq) + abs(edge) / 2 + 1, RGB565(120, 82, 18));
  gfx->fillEllipse(cx, cy, R + 5, (int)((R + 5) * sq) + 1, RGB565(232, 182, 60));
  const uint16_t *face = (c >= 0) ? DEC_POS_COIN : DEC_NEG_COIN;
  decDisc(face, DEC_COIN, cx, cy, R, sq);
}

// ---------------------------------------------------------------- sound

#define AUD_MCK  16
#define AUD_BCK  9
#define AUD_WS   45
#define AUD_DO   8
#define AUD_DI   10
#define AUD_PA   46                      // amplifier enable, HIGH = speaker live
#define AUD_VOLUME 80                    // codec volume 0..100

static I2SClass decI2s;
static int  audState = 0;                // 0 not tried, 1 ready, -1 failed (then stay silent)
static volatile bool sndStop = false;
static volatile bool sndBusy = false;

// Bring up I2S and the codec, once, on the first toss. Any failure leaves the Decider working
// silently rather than breaking it.
bool decAudioInit() {
  if (audState) return audState > 0;
  audState = -1;
  pinMode(AUD_PA, OUTPUT);
  digitalWrite(AUD_PA, LOW);
  Wire.beginTransmission(ES8311_ADDRRES_0);   // same I2C bus as the touch, already running
  if (Wire.endTransmission() != 0) { Serial.println("audio  : ES8311 not answering - Decider stays silent"); return false; }
  decI2s.setPins(AUD_BCK, AUD_WS, AUD_DO, AUD_DI, AUD_MCK);
  if (!decI2s.begin(I2S_MODE_STD, DEC_SND_RATE, I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO, I2S_STD_SLOT_BOTH)) {
    Serial.println("audio  : I2S did not start - Decider stays silent");
    return false;
  }
  es8311_handle_t codec = es8311_create(0, ES8311_ADDRRES_0);
  es8311_clock_config_t clk = {};
  clk.mclk_from_mclk_pin = true;
  clk.mclk_frequency = DEC_SND_RATE * 256;
  clk.sample_frequency = DEC_SND_RATE;
  int got = 0;
  if (!codec || es8311_init(codec, &clk, ES8311_RESOLUTION_16, ES8311_RESOLUTION_16) != ESP_OK ||
      es8311_sample_frequency_config(codec, clk.mclk_frequency, clk.sample_frequency) != ESP_OK ||
      es8311_voice_volume_set(codec, AUD_VOLUME, &got) != ESP_OK) {
    Serial.println("audio  : ES8311 setup failed - Decider stays silent");
    return false;
  }
  es8311_microphone_config(codec, false);
  audState = 1;
  Serial.printf("audio  : ES8311 + I2S ready, %d Hz, volume %d; drum roll %.2f s, crash at %d ms\n",
                DEC_SND_RATE, got, DEC_SND_LEN / (float)DEC_SND_RATE, DEC_SND_CRASH * 1000 / DEC_SND_RATE);
  return true;
}

// Core-0 task: stream the PCM as interleaved stereo in small blocks. i2s.write() blocks until the
// DMA has room, which is what paces it. Ends with silence, then the amp off.
void decSoundTask(void *arg) {
  static int16_t blk[256 * 2];
  uint32_t t0 = millis();
  int pos = 0;
  while (pos < DEC_SND_LEN && !sndStop) {
    int n = DEC_SND_LEN - pos; if (n > 256) n = 256;
    for (int i = 0; i < n; i++) { blk[2 * i] = blk[2 * i + 1] = DEC_SND[pos + i]; }
    decI2s.write((uint8_t *)blk, n * 4);
    pos += n;
  }
  memset(blk, 0, sizeof(blk));
  for (int i = 0; i < 6; i++) decI2s.write((uint8_t *)blk, sizeof(blk));   // flush the DMA with silence
  digitalWrite(AUD_PA, LOW);
  Serial.printf("audio  : drum roll %s after %lu ms\n", sndStop ? "stopped" : "finished",
                (unsigned long)(millis() - t0));
  sndBusy = false;
  vTaskDelete(nullptr);
}

void decSoundStop() {
  if (!sndBusy) return;
  sndStop = true;
  for (int i = 0; i < 50 && sndBusy; i++) delay(4);
}

void decSoundStart() {
  if (!decAudioInit()) return;
  decSoundStop();                       // a new toss cuts off the previous one's tail
  sndStop = false;
  sndBusy = true;
  digitalWrite(AUD_PA, HIGH);
  if (xTaskCreatePinnedToCore(decSoundTask, "drumroll", 4096, nullptr, 5, nullptr, 0) != pdPASS) {
    sndBusy = false;
    digitalWrite(AUD_PA, LOW);
    Serial.println("audio  : could not start the sound task");
  }
}

// ---------------------------------------------------------------- the app

void decDrawPill() {
  gfx->fillRoundRect(DEC_PILL_X, DEC_PILL_Y, DEC_PILL_W, DEC_PILL_H, 14, RGB565(10, 14, 30));
  gfx->drawRoundRect(DEC_PILL_X, DEC_PILL_Y, DEC_PILL_W, DEC_PILL_H, 14, RGB565(120, 200, 255));
  gfx->drawFastVLine(DEC_PILL_X + DEC_PILL_W / 2, DEC_PILL_Y + 6, DEC_PILL_H - 12, RGB565(70, 90, 120));
  gfx->setTextSize(2);
  gfx->setTextColor(RGB565_WHITE);
  gfx->setCursor(DEC_PILL_X + 25, DEC_PILL_Y + 11);
  gfx->print("AGAIN");
  gfx->setCursor(DEC_PILL_X + DEC_PILL_W / 2 + 31, DEC_PILL_Y + 11);
  gfx->print("HOME");
}

// True if BOOT was pressed; also takes the badge home, so callers just return.
bool decBootHome() {
  if (!bootButtonHit()) return false;
  decSoundStop();
  Serial.println("btn    : BOOT pressed -> main screen (from the decider)");
  showScreen(ST_HOME);
  return true;
}

void showDecider() {
  decMakeBg();
  if (!decBg) {
    gfx->fillScreen(RGB565_BLACK);
    centred(226, "no memory for the decider", 2, RGB565(255, 120, 120));
    gfx->flush();
    return;
  }

  decResult = (esp_random() & 1) ? 1 : 0;        // decided up front; the toss just shows it
  decTosses++;
  if (decResult) decYes++;
  Serial.printf("decider: toss %lu -> %s (%lu approved so far)\n", (unsigned long)decTosses,
                decResult ? "APPROVED" : "DISAPPROVED", (unsigned long)decYes);

  // Full backdrop once, then only the coin's patch is restored per frame.
  memcpy(gfx->getFramebuffer(), decBg, (size_t)LCD_WIDTH * LCD_HEIGHT * 2);
  decDX0 = 0; decDY0 = 0; decDX1 = LCD_WIDTH - 1; decDY1 = LCD_HEIGHT - 1;

  // Planned spin: whole turns for approved, an extra half-turn for disapproved, so the last
  // frame lands flat on the chosen face.
  const float total = DEC_TURNS * 2.0f * PI + (decResult ? 0.0f : PI);
  // Peak checked against the round glass: at the top the coin is centred at y~155 with R~102,
  // so it never leaves the circle (a peak of 200 put its top past the edge).
  const int restY = 300, landY = 250, peak = 120;
  int cx = 233, cy = restY, R = 66;

  // Timed, not counted: frame f shows the throw at the moment it is drawn, so the crash in the
  // sound (at DEC_TOSS_MS) lands with the coin whatever the frame rate is. The last frame is
  // always exactly t = 1, flat on the chosen face.
  decSoundStart();
  uint32_t t0 = millis();
  int frames = 0;
  for (bool last = false; !last; frames++) {
    uint32_t el = millis() - t0;
    if (el >= DEC_TOSS_MS) { el = DEC_TOSS_MS; last = true; }
    float t = (float)el / DEC_TOSS_MS;
    float h = 4.0f * t * (1.0f - t);                // 0 -> 1 -> 0: height of the throw
    float ease = 1.0f - (1.0f - t) * (1.0f - t);     // spin fast at first, slowing to land
    cy = (int)(restY + (landY - restY) * t - peak * h);
    R = (int)(66 + 36 * h);
    float theta = total * ease;

    decRestore(decDX0, decDY0, decDX1, decDY1);
    // Shadow on the floor: wide and dark when low, small and faint when high.
    int sw = (int)(70 * (1.0f - 0.55f * h)), sh = (int)(11 * (1.0f - 0.55f * h));
    gfx->fillEllipse(233, 398, sw, sh, RGB565(2, 3, 8));
    decCoin(cx, cy, R, theta);

    // Bounding box of what was drawn, for the next frame's restore.
    int ox0 = decDX0, oy0 = decDY0, ox1 = decDX1, oy1 = decDY1;
    int edge = (int)(R * 0.10f) + 8;
    decDX0 = cx - R - 8;            decDX1 = cx + R + 8;
    decDY0 = cy - R - edge;         decDY1 = cy + R + edge;
    if (decDY1 < 398 + 12) decDY1 = 398 + 12;        // include the shadow
    if (decDX0 > 233 - 72) decDX0 = 233 - 72;
    if (decDX1 < 233 + 72) decDX1 = 233 + 72;
    // Send only what changed: the old patch (now backdrop again) plus the new coin. About a
    // third of the screen, so frames go out ~2-3x faster than a full flush and the throw is smoother.
    int ux0 = min(ox0, decDX0), uy0 = min(oy0, decDY0), ux1 = max(ox1, decDX1), uy1 = max(oy1, decDY1);
    flushRect(ux0, uy0, ux1 - ux0 + 1, uy1 - uy0 + 1);

    if (decBootHome()) return;
  }
  Serial.printf("decider: toss animation %lu ms (%d frames, %.0f fps)\n",
                (unsigned long)(millis() - t0), frames, frames * 1000.0f / (millis() - t0 + 1));
  delay(220);                                        // a beat on the landed coin

  // Zoom: the landed coin grows into the full-screen badge, drifting to the centre.
  const uint16_t *full = decResult ? DEC_POS : DEC_NEG;
  for (int f = 1; f <= DEC_ZOOM; f++) {
    float t = (float)f / DEC_ZOOM;
    float e = t * t * (3.0f - 2.0f * t);             // smoothstep
    int r = (int)(R + (233 - R) * e);
    int y = (int)(cy + (233 - cy) * e);
    decRestore(decDX0, decDY0, decDX1, decDY1);
    gfx->fillEllipse(233, y, r + 5, r + 5, RGB565(232, 182, 60));
    decDisc(full, DEC_PANEL, 233, y, r, 1.0f);
    int ox0 = decDX0, oy0 = decDY0, ox1 = decDX1, oy1 = decDY1;
    decDX0 = 233 - r - 6; decDX1 = 233 + r + 6; decDY0 = y - r - 6; decDY1 = y + r + 6;
    int ux0 = min(ox0, decDX0), uy0 = min(oy0, decDY0), ux1 = max(ox1, decDX1), uy1 = max(oy1, decDY1);
    flushRect(ux0, uy0, ux1 - ux0 + 1, uy1 - uy0 + 1);
    if (decBootHome()) return;
  }

  // Exact final frame: the badge pixel for pixel.
  memcpy(gfx->getFramebuffer(), full, (size_t)LCD_WIDTH * LCD_HEIGHT * 2);
  gfx->flush();

  // Let the result speak for a moment, then offer AGAIN | HOME. BOOT still works meanwhile.
  uint32_t shown = millis();
  while (millis() - shown < DEC_HINT_MS) {
    if (decBootHome()) return;
    delay(10);
  }
  decDrawPill();
  flushRect(DEC_PILL_X - 4, DEC_PILL_Y - 4, DEC_PILL_W + 8, DEC_PILL_H + 8);
  Serial.println("decider: result up - tap to toss again, HOME or BOOT for the main screen");
  // Back to loop(): taps on this screen arrive in handleTap() -> deciderTap().
}

// A tap on the result screen. HOME (right half of the pill) goes to the main screen; anything
// else tosses again.
void deciderTap(int x, int y) {
  bool onPill = x >= DEC_PILL_X - 10 && x <= DEC_PILL_X + DEC_PILL_W + 10 &&
                y >= DEC_PILL_Y - 12 && y <= DEC_PILL_Y + DEC_PILL_H + 12;
  if (onPill && x >= DEC_PILL_X + DEC_PILL_W / 2) {
    Serial.println("         -> decider: home");
    showScreen(ST_HOME);
  } else {
    Serial.println("         -> decider: toss again");
    showScreen(ST_DECIDER);
  }
}

// The home-screen icon: a thumbs up, in the same light-blue line style as the other app icons
// (it used to be a gold coin with a "?"). Shapes are in units of r so the carousel can draw it big
// in the middle and small at the sides; the thumb points up out of a fist, with a cuff behind.
void drawDeciderIcon(int cx, int cy, int r, uint16_t fg, uint16_t bg) {
  cx -= (r * 8) / 100;                              // the glyph is a little wider on the left
  int rad = r / 6; if (rad < 2) rad = 2;
  gfx->fillRect(cx - (r * 78) / 100, cy - (r * 2) / 100, (r * 32) / 100, (r * 74) / 100, fg);       // cuff
  gfx->fillRoundRect(cx - (r * 38) / 100, cy - (r * 10) / 100, r, (r * 82) / 100, rad, fg);         // fist
  gfx->fillRoundRect(cx - (r * 30) / 100, cy - (r * 80) / 100, (r * 36) / 100, (r * 82) / 100,
                     (r * 17) / 100 > 2 ? (r * 17) / 100 : 2, fg);                                   // thumb
  int lw = r / 16; if (lw < 1) lw = 1;
  const int crease[3] = { 14, 33, 52 };                                                             // fingers
  for (int k = 0; k < 3; k++)
    gfx->fillRect(cx + (r * 10) / 100, cy + (r * crease[k]) / 100 - lw / 2, (r * 52) / 100 + 1, lw + 1, bg);
  gfx->fillRect(cx + (r * 6) / 100 - lw / 2, cy - (r * 10) / 100, lw + 1, (r * 12) / 100, bg);       // thumb seam
}
