#!/usr/bin/env python3
"""Synthesize the slap sounds for Badge/sos_sounds.h - no samples from anywhere, so no licence
questions. 16 kHz mono int16, the badge's audio rate.

  SND_SLAP   being slapped: a short whoosh, a sharp smack (filtered noise burst with a 1 ms attack)
             and a low thump under it.
  SND_SWISH  sending a slap: just the whoosh, rising.
"""
import sys
from pathlib import Path
import numpy as np

RATE = 16000
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "Badge" / "sos_sounds.h"
rng = np.random.default_rng(7)


def bandpass(x, lo, hi):
    f = np.fft.rfft(x)
    fr = np.fft.rfftfreq(len(x), 1 / RATE)
    f[(fr < lo) | (fr > hi)] = 0
    return np.fft.irfft(f, len(x))


def whoosh(ms, rise=True):
    n = RATE * ms // 1000
    t = np.linspace(0, 1, n)
    env = np.sin(np.pi * t) ** 2
    noise = rng.standard_normal(n)
    # sweep the band upwards by mixing three bands with moving weights
    lo, mid, hi = bandpass(noise, 300, 900), bandpass(noise, 900, 2500), bandpass(noise, 2500, 6000)
    w = t if rise else 1 - t
    return env * (lo * (1 - w) + mid * 0.8 + hi * w) * 0.35


def smack():
    n = RATE * 260 // 1000
    t = np.arange(n) / RATE
    attack = np.minimum(1, t / 0.001)
    crack = bandpass(rng.standard_normal(n), 900, 7000) * np.exp(-t / 0.028) * attack
    thump = np.sin(2 * np.pi * 110 * t) * np.exp(-t / 0.06) * attack * 0.9
    sting = bandpass(rng.standard_normal(n), 3000, 7500) * np.exp(-t / 0.09) * 0.12
    return crack * 1.6 + thump + sting


def norm(x, peak=0.92):
    return x / np.max(np.abs(x)) * peak


def to_c(name, x):
    v = np.clip(norm(x) * 32767, -32767, 32767).astype(np.int16)
    rows = [",".join(str(int(s)) for s in v[i:i + 24]) for i in range(0, len(v), 24)]
    return f"#define {name}_LEN {len(v)}\nstatic const int16_t {name}[{len(v)}] = {{\n" + ",\n".join(rows) + "\n};\n\n"


slap = np.concatenate([whoosh(140) * 0.7, smack()])
swish = whoosh(260)
OUT.write_text("// Generated by tools/make_sos_sounds.py - do not edit by hand.\n#pragma once\n#include <stdint.h>\n\n"
               + to_c("SND_SLAP", slap) + to_c("SND_SWISH", swish))
print(f"wrote {OUT}: slap {len(slap) / RATE:.2f} s, swish {len(swish) / RATE:.2f} s")
