#!/usr/bin/env python3
"""Cut the Decider drum roll to the coin toss and compile it into the Badge firmware.

Source : C:\\Users\\brain\\Downloads\\ThanksDanny\\chooser\\drummroll.mp3   (needs ffmpeg on PATH)
Output : <sketch>\\Badge\\decider_sound.h   (16 kHz mono 16-bit PCM, ~130 kB of flash)

The original is 8.8 s: a roll for ~5.1 s, a cymbal crash at ~5.13 s, then silence. The toss on the
badge lasts TOSS_MS, so the roll is cut to that length and crossfaded straight into the crash:
the crash lands on the frame where the coin lands. The crash onset is FOUND (first 10 ms window
after 3 s whose loudness jumps past 3x the roll's), not hard-coded, so a different drum roll
file works as long as it ends in a hit.
"""
import subprocess, sys
from pathlib import Path
import numpy as np

SRC = Path(r"C:\Users\brain\Downloads\ThanksDanny\chooser\drummroll.mp3")
OUT = Path(r"C:\Users\brain\Documents\Arduino\ThanksDanny\Badge\decider_sound.h")
if len(sys.argv) == 3:
    SRC, OUT = Path(sys.argv[1]), Path(sys.argv[2])
RATE = 16000
TOSS_MS = 2400          # must match DEC_TOSS_MS in Decider.ino
XFADE_MS = 40
TAIL_MS = 1700          # how much of the crash to keep after its onset
PEAK = 26000            # normalise to this (about -2 dBFS)


def main():
    raw = subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-i", str(SRC),
                          "-ac", "1", "-ar", str(RATE), "-f", "s16le", "-"],
                         check=True, capture_output=True).stdout
    a = np.frombuffer(raw, np.int16).astype(np.float32)
    w = RATE // 100
    env = np.array([np.sqrt(np.mean(a[i:i + w] ** 2)) for i in range(0, len(a) - w, w)])
    start = int(3.0 * 100)
    roll_level = np.median(env[50:start])
    hits = np.nonzero(env[start:] > 3.0 * roll_level)[0]
    if not len(hits):
        sys.exit("no crash found after 3 s - is this the right file?")
    onset = (start + hits[0]) * w
    print(f"  source {len(a) / RATE:.2f} s, roll level {roll_level:.0f}, crash at {onset / RATE * 1000:.0f} ms")

    xf = RATE * XFADE_MS // 1000
    cut = RATE * TOSS_MS // 1000                 # crash must start sounding here
    pre = xf // 2
    roll = a[:cut - pre + xf].copy()
    crash = a[onset - pre - 0: onset - pre + RATE * TAIL_MS // 1000].copy()
    ramp = np.linspace(0, 1, xf, dtype=np.float32)
    roll[-xf:] = roll[-xf:] * (1 - ramp) + crash[:xf] * ramp
    out = np.concatenate([roll, crash[xf:]])
    fade = RATE * 300 // 1000                    # fade the crash's tail out, no click at the end
    out[-fade:] *= np.linspace(1, 0, fade, dtype=np.float32)
    out *= PEAK / max(1.0, np.abs(out).max())
    pcm = np.clip(out, -32767, 32767).astype(np.int16)
    crash_at = cut
    lines = ["// Generated by tools/prep_decider_sound.py - do not edit by hand; re-run the script.\n",
             "#pragma once\n#include <stdint.h>\n\n",
             f"#define DEC_SND_RATE {RATE}\n",
             f"#define DEC_SND_LEN {len(pcm)}\n",
             f"#define DEC_SND_CRASH {crash_at}   // sample where the crash starts = coin lands\n\n",
             f"static const int16_t DEC_SND[{len(pcm)}] = {{\n"]
    for i in range(0, len(pcm), 20):
        lines.append(",".join(str(int(v)) for v in pcm[i:i + 20]) + ",\n")
    lines.append("};\n")
    OUT.write_text("".join(lines))
    print(f"  wrote {OUT}: {len(pcm) / RATE:.2f} s, crash at {crash_at / RATE * 1000:.0f} ms, "
          f"{len(pcm) * 2 / 1024:.0f} kB in flash")
    pcm.tofile(OUT.with_name("decider_sound_check.raw"))


if __name__ == "__main__":
    main()
