#!/usr/bin/env python3
"""Startup splash: picture + sound compiled into the Badge firmware (Badge/startup_assets.h).

Source : C:\\Users\\brain\\Downloads\\ThanksDanny\\startup\\  (the first .jpg/.png and the first .mp3)
Output : <sketch>\\Badge\\startup_assets.h                     (needs ffmpeg on PATH for the sound)

Compiled in rather than downloaded or put on LittleFS, because it has to appear the instant the
badge powers on - before Wi-Fi, before anything else is ready - and must survive a filesystem
reflash.

  picture : cropped to a square from near the top (BIAS: 0 = top edge, 1 = bottom), 466x466,
            outside the round glass set to black, stored as raw RGB565 (434 kB) so it is on
            screen with a memcpy and one flush, no decode.
  sound   : re-encoded to 16 kHz mono MP3 at 48 kbit/s, the rate the badge's audio path runs
            at, and stored as MP3 bytes (decoded on the badge by the same Helix decoder as
            Rumours).
"""
import subprocess, sys
from pathlib import Path
import numpy as np
from PIL import Image

SRC = Path(r"C:\Users\brain\Downloads\ThanksDanny\startup")
OUT = Path(r"C:\Users\brain\Documents\Arduino\ThanksDanny\Badge\startup_assets.h")
if len(sys.argv) == 3:
    SRC, OUT = Path(sys.argv[1]), Path(sys.argv[2])
SIZE = 466
BIAS = 0.08          # chosen from renders through the round mask: sign, three faces, patch


def picture(path):
    im = Image.open(path).convert("RGB")
    side = min(im.size)
    left = (im.width - side) // 2
    top = int((im.height - side) * BIAS)
    sq = im.crop((left, top, left + side, top + side)).resize((SIZE, SIZE), Image.LANCZOS)
    a = np.asarray(sq).astype(np.float32)
    yy, xx = np.mgrid[0:SIZE, 0:SIZE]
    edge = np.clip(SIZE / 2 - np.hypot(xx - (SIZE - 1) / 2, yy - (SIZE - 1) / 2), 0, 1)[..., None]
    a = (a * edge).astype(np.uint16)
    v = ((a[..., 0] >> 3) << 11) | ((a[..., 1] >> 2) << 5) | (a[..., 2] >> 3)
    return v.ravel(), Image.fromarray((a).astype(np.uint8))


def sound(path):
    return subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-i", str(path),
                           "-map_metadata", "-1", "-vn", "-ac", "1", "-ar", "16000",
                           "-codec:a", "libmp3lame", "-b:a", "48k", "-id3v2_version", "0",
                           "-write_xing", "0", "-f", "mp3", "-"],
                          check=True, capture_output=True).stdout


def main():
    pics = sorted([p for p in SRC.iterdir() if p.suffix.lower() in (".jpg", ".jpeg", ".png")])
    mp3s = sorted(SRC.glob("*.mp3"))
    if not pics:
        sys.exit(f"no picture in {SRC}")
    px, preview = picture(pics[0])
    snd = sound(mp3s[0]) if mp3s else b""
    lines = ["// Generated by tools/prep_startup.py - do not edit by hand; re-run the script.\n",
             f"// picture: {pics[0].name}\n// sound  : {mp3s[0].name if mp3s else '(none)'}\n",
             "#pragma once\n#include <stdint.h>\n\n",
             f"#define STARTUP_MP3_LEN {len(snd)}\n\n",
             f"static const uint16_t STARTUP_IMG[{SIZE * SIZE}] = {{\n"]
    for i in range(0, len(px), 24):
        lines.append(",".join(f"0x{x:04X}" for x in px[i:i + 24]) + ",\n")
    lines.append("};\n\n")
    lines.append(f"static const uint8_t STARTUP_MP3[{max(1, len(snd))}] = {{\n")
    data = snd or b"\0"
    for i in range(0, len(data), 32):
        lines.append(",".join(str(b) for b in data[i:i + 32]) + ",\n")
    lines.append("};\n")
    OUT.write_text("".join(lines))
    preview.save(OUT.with_name("startup_preview.png"))
    print(f"  picture {pics[0].name} -> {SIZE}x{SIZE} RGB565 ({SIZE * SIZE * 2 // 1024} kB)")
    print(f"  sound   {mp3s[0].name if mp3s else '-'} -> {len(snd) // 1024} kB MP3, 16 kHz mono")
    print(f"  wrote {OUT}")


if __name__ == "__main__":
    main()
