#!/usr/bin/env python3
"""Turn the two Decider badges into RGB565 arrays compiled into the Badge firmware.

Source : C:\\Users\\brain\\Downloads\\ThanksDanny\\chooser\\positive.png / negative.jpg
Output : <sketch>\\Badge\\decider_assets.h

Why compiled-in rather than on LittleFS: adding files to the filesystem means rebuilding and
reflashing the whole 23 MB image (~3 min) and it wipes the cached GitHub pictures. Raw RGB565 in
the app partition costs ~1 MB of the 4.8 MB app space, needs no JPEG decode on the badge (the
result appears the instant the coin lands), and ships with an ordinary sketch upload.

The badges are round with a fake checkerboard baked into the corners (not real transparency), so
each is cropped to its navy outer ring, which then sits exactly on the edge of the round glass;
everything outside the circle is set to black.

  DEC_POS / DEC_NEG             466x466  full-screen result
  DEC_POS_COIN / DEC_NEG_COIN   COIN x COIN coin faces for the toss animation
"""
import sys
from pathlib import Path
import numpy as np
from PIL import Image

SRC = Path(r"C:\Users\brain\Downloads\ThanksDanny\chooser")
OUT = Path(r"C:\Users\brain\Documents\Arduino\ThanksDanny\Badge\decider_assets.h")
if len(sys.argv) == 3:
    SRC, OUT = Path(sys.argv[1]), Path(sys.argv[2])
PANEL = 466
COIN = 200


def find_circle(img):
    a = np.asarray(img.convert("RGB")).astype(int)
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    navy = (b > r + 25) & ((r + g + b) / 3 < 140)
    ys, xs = np.nonzero(navy)
    # Trim 0.2% at each end so a stray navy speck in the background cannot stretch the box.
    x0, x1 = np.percentile(xs, [0.2, 99.8])
    y0, y1 = np.percentile(ys, [0.2, 99.8])
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    rad = max(x1 - x0, y1 - y0) / 2 * 1.012       # a hair outside the ring
    return cx, cy, rad


def square(img, size):
    cx, cy, rad = find_circle(img)
    box = (int(round(cx - rad)), int(round(cy - rad)), int(round(cx + rad)), int(round(cy + rad)))
    sq = img.convert("RGB").crop(box).resize((size, size), Image.LANCZOS)
    a = np.asarray(sq).astype(np.float32)
    yy, xx = np.mgrid[0:size, 0:size]
    d = np.hypot(xx - (size - 1) / 2, yy - (size - 1) / 2)
    edge = np.clip(size / 2 - d, 0, 1)[..., None]  # 1-px anti-aliased edge, black outside
    return (a * edge).astype(np.uint8), (cx, cy, rad)


def rgb565(a):
    r = a[..., 0].astype(np.uint16) >> 3
    g = a[..., 1].astype(np.uint16) >> 2
    b = a[..., 2].astype(np.uint16) >> 3
    return (r << 11) | (g << 5) | b


def emit(name, arr, w, h):
    v = rgb565(arr).ravel()
    lines = [f"// {name}: {w}x{h} RGB565, row-major, native byte order\n",
             f"static const uint16_t {name}[{w * h}] = {{\n"]
    for i in range(0, len(v), 24):
        lines.append(",".join(f"0x{x:04X}" for x in v[i:i + 24]) + ",\n")
    lines.append("};\n\n")
    return "".join(lines)


def main():
    pos = Image.open(SRC / "positive.png")
    neg = Image.open(SRC / "negative.jpg")
    out = ["// Generated by tools/prep_decider.py - do not edit by hand; re-run the script.\n",
           "#pragma once\n#include <stdint.h>\n\n",
           f"#define DEC_PANEL {PANEL}\n#define DEC_COIN {COIN}\n\n"]
    previews = []
    for tag, img in (("POS", pos), ("NEG", neg)):
        full, c = square(img, PANEL)
        coin, _ = square(img, COIN)
        print(f"  {tag}: source {img.size}, circle centre ({c[0]:.0f},{c[1]:.0f}) r {c[2]:.0f}")
        out.append(emit(f"DEC_{tag}", full, PANEL, PANEL))
        out.append(emit(f"DEC_{tag}_COIN", coin, COIN, COIN))
        previews.append(Image.fromarray(full))
    OUT.write_text("".join(out))
    print(f"  wrote {OUT} ({OUT.stat().st_size / 1e6:.1f} MB of source, "
          f"{2 * 2 * (PANEL * PANEL + COIN * COIN) / 1024:.0f} kB in flash)")
    prev = Image.new("RGB", (PANEL * 2 + 10, PANEL))
    prev.paste(previews[0], (0, 0)); prev.paste(previews[1], (PANEL + 10, 0))
    prev.save(OUT.with_name("decider_preview.png"))


if __name__ == "__main__":
    main()
